// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using findteachersforresearch.Data;

#nullable disable

namespace findteachersforresearch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250212120739_ur-details-3")]
    partial class urdetails3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("findteachersforresearch.Models.Employment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstablishmentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstablishmentCounty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstablishmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstablishmentSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstablishmentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstablishmentTown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstablishmentTypeGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstablishmentTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenInTPSDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Employment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmploymentType = "Part Time Regular",
                            EstablishmentCode = "1234",
                            EstablishmentCounty = "Derbyshire",
                            EstablishmentName = "Gladys Buxton School",
                            EstablishmentSource = "GIAS",
                            EstablishmentStatus = "Open",
                            EstablishmentTown = "Dronfield",
                            EstablishmentTypeGroupName = "Local Authority Maintained Schools",
                            EstablishmentTypeName = "Foundation School",
                            LaCode = "925",
                            LastSeenInTPSDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 1,
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            EmploymentType = "Part Time Regular",
                            EstablishmentCode = "5678",
                            EstablishmentCounty = "Derbyshire",
                            EstablishmentName = "Holmesdale School",
                            EstablishmentSource = "GIAS",
                            EstablishmentStatus = "Open",
                            EstablishmentTown = "Dronfield",
                            EstablishmentTypeGroupName = "Local Authority Maintained Schools",
                            EstablishmentTypeName = "Foundation School",
                            LaCode = "925",
                            LastSeenInTPSDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 1,
                            StartDate = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            EmploymentType = "Full Time",
                            EstablishmentCode = "9101",
                            EstablishmentCounty = "Derbyshire",
                            EstablishmentName = "Greenwood Academy",
                            EstablishmentSource = "GIAS",
                            EstablishmentStatus = "Open",
                            EstablishmentTown = "Chesterfield",
                            EstablishmentTypeGroupName = "Academies",
                            EstablishmentTypeName = "Academy",
                            LaCode = "925",
                            LastSeenInTPSDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 2,
                            StartDate = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            EmploymentType = "Full Time",
                            EstablishmentCode = "4545",
                            EstablishmentCounty = "Lancashire",
                            EstablishmentName = "All Saints School",
                            EstablishmentSource = "GIAS",
                            EstablishmentStatus = "Open",
                            EstablishmentTown = "Lancaster",
                            EstablishmentTypeGroupName = "Free Schools",
                            EstablishmentTypeName = "Free School",
                            LaCode = "567",
                            LastSeenInTPSDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 3,
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            EmploymentType = "Full Time",
                            EstablishmentCode = "4674",
                            EstablishmentCounty = "Cornwall",
                            EstablishmentName = "Stonelow School",
                            EstablishmentSource = "GIAS",
                            EstablishmentStatus = "Open",
                            EstablishmentTown = "Helston",
                            EstablishmentTypeGroupName = "Religious Schools",
                            EstablishmentTypeName = "Religious School",
                            LaCode = "223",
                            LastSeenInTPSDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 4,
                            StartDate = new DateTime(2020, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("findteachersforresearch.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailPersonal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OptedOutOfResearch")
                        .HasColumnType("boolean");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailPersonal = "myles@gmail.com",
                            EmailWork = "myles@work.com",
                            FirstName = "Myles",
                            Gender = "Male",
                            LastName = "Rabbit",
                            Nino = "RAB54",
                            OptedOutOfResearch = false,
                            ReferenceNumber = "1234567"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1985, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailPersonal = "jane@gmail.com",
                            EmailWork = "jane@work.com",
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Smith",
                            Nino = "SMI89",
                            OptedOutOfResearch = false,
                            ReferenceNumber = "7654321"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1975, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailPersonal = "doris@gmail.com",
                            EmailWork = "doris@work.com",
                            FirstName = "Doris",
                            Gender = "Female",
                            LastName = "Madeline",
                            Nino = "DMI869",
                            OptedOutOfResearch = true,
                            ReferenceNumber = "7678890"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1989, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailPersonal = "ronnie@gmail.com",
                            EmailWork = "ronnie@work.com",
                            FirstName = "Ronnie",
                            Gender = "Male",
                            LastName = "Hotdogs",
                            Nino = "RON345",
                            OptedOutOfResearch = false,
                            ReferenceNumber = "99888776"
                        });
                });

            modelBuilder.Entity("findteachersforresearch.Models.ProfStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ITTCourse")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ITTStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ProfStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonId = 1,
                            StatusName = "Qualified Teacher (Trained)"
                        },
                        new
                        {
                            Id = 2,
                            PersonId = 2,
                            StatusName = "Qualified Teacher: By virtue of overseas qualifications"
                        },
                        new
                        {
                            Id = 3,
                            ITTCourse = "Applied Physics",
                            ITTStartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 3,
                            StatusName = "Trainee"
                        },
                        new
                        {
                            Id = 4,
                            ITTCourse = "Geography",
                            ITTStartDate = new DateTime(2021, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 4,
                            StatusName = "Qualified Teacher (Trained)"
                        });
                });

            modelBuilder.Entity("findteachersforresearch.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EYAwardDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NPQAwardDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("QTLSAwardDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("QTSAwardDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Qualification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonId = 1,
                            QTSAwardDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            EYAwardDate = new DateTime(2017, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonId = 2,
                            QTSAwardDate = new DateTime(2010, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            PersonId = 4,
                            QTSAwardDate = new DateTime(2009, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("findteachersforresearch.Models.Research", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResearchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResearchName")
                        .HasColumnType("text");

                    b.Property<string>("UserResearcherName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Research");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Notes = "Went really well.",
                            PersonId = 1,
                            ResearchDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResearchName = "Teacher Vacancies New Feature X",
                            UserResearcherName = "Will@education.gov.uk"
                        },
                        new
                        {
                            Id = 2,
                            Notes = "Not a very engaged participant",
                            PersonId = 2,
                            ResearchDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ResearchName = "TRS New Feature Y",
                            UserResearcherName = "Steph@education.gov.uk"
                        });
                });

            modelBuilder.Entity("findteachersforresearch.Models.Employment", b =>
                {
                    b.HasOne("findteachersforresearch.Models.Person", null)
                        .WithMany("Employments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("findteachersforresearch.Models.ProfStatus", b =>
                {
                    b.HasOne("findteachersforresearch.Models.Person", null)
                        .WithMany("ProfStatuses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("findteachersforresearch.Models.Qualification", b =>
                {
                    b.HasOne("findteachersforresearch.Models.Person", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("findteachersforresearch.Models.Research", b =>
                {
                    b.HasOne("findteachersforresearch.Models.Person", null)
                        .WithMany("Research")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("findteachersforresearch.Models.Person", b =>
                {
                    b.Navigation("Employments");

                    b.Navigation("ProfStatuses");

                    b.Navigation("Qualifications");

                    b.Navigation("Research");
                });
#pragma warning restore 612, 618
        }
    }
}
